.gitignore, config/marklogic-sink-marklogic-ssl.properties, src/main/java/com/marklogic/kafka/connect/sink/DefaultSinkRecordConverter.java, src/main/java/com/marklogic/kafka/connect/sink/MarkLogicSinkConfig.java
Reverts marklogic-community/kafka-marklogic-connector#10
=> Revert "Feature/issue7"

src/main/java/com/marklogic/client/ext/document/DocumentWriteOperationBuilder.java, src/main/java/com/marklogic/client/ext/document/RecordContent.java, src/main/java/com/marklogic/kafka/connect/sink/DefaultSinkRecordConverter.java
Didn't know Java allowed this! Intellij was complaining about it though, and folders are expected to match packages by convention.
=> Fixing package in RecordContent

.editorconfig, src/main/java/com/marklogic/client/ext/document/DocumentWriteOperationBuilder.java, src/main/java/com/marklogic/client/ext/document/RecordContent.java, src/main/java/com/marklogic/client/id/strategy/DefaultStrategy.java, src/main/java/com/marklogic/client/id/strategy/HashedJSONPathsStrategy.java, src/main/java/com/marklogic/client/id/strategy/HashedKafkaMetaStrategy.java, src/main/java/com/marklogic/client/id/strategy/IdStrategy.java, src/main/java/com/marklogic/client/id/strategy/IdStrategyFactory.java, src/main/java/com/marklogic/client/id/strategy/JSONPathStrategy.java, src/main/java/com/marklogic/client/id/strategy/KafkaMetaStrategy.java, src/main/java/com/marklogic/kafka/connect/DatabaseClientConfigBuilder.java, src/main/java/com/marklogic/kafka/connect/DefaultDatabaseClientConfigBuilder.java, src/main/java/com/marklogic/kafka/connect/sink/DefaultSinkRecordConverter.java, src/main/java/com/marklogic/kafka/connect/sink/MarkLogicSinkConfig.java, src/main/java/com/marklogic/kafka/connect/sink/MarkLogicSinkConnector.java, src/main/java/com/marklogic/kafka/connect/sink/MarkLogicSinkTask.java, src/main/java/com/marklogic/kafka/connect/sink/RunFlowWriteBatchListener.java, src/main/java/com/marklogic/kafka/connect/sink/SinkRecordConverter.java, src/test/java/com/marklogic/kafka/connect/BuildDatabaseClientConfigTest.java, src/test/java/com/marklogic/kafka/connect/sink/BuildServerTransformTest.java, src/test/java/com/marklogic/kafka/connect/sink/BuildSuccessListenerTest.java, src/test/java/com/marklogic/kafka/connect/sink/ConvertSinkRecordTest.java, src/test/java/com/marklogic/kafka/connect/sink/MockWriteBatcher.java, src/test/java/com/marklogic/kafka/connect/sink/RunFlowWriteBatchListenerTest.java, src/test/resources/logback.xml
No functional changes in any files, just formatting changes
=> Added .editorconfig, formatted for spaces

README.md, build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, src/test/java/com/marklogic/kafka/connect/sink/ConvertSinkRecordTest.java
Also modified ConvertSinkRecordTest to use Jackson instead of gson so we can drop the gson dependency.
=> Bumping dependencies and using shadowJar

CONTRIBUTING.md, README.md, build.gradle, config/marklogic-sink.properties, gradle.properties, src/main/java/com/marklogic/kafka/connect/sink/MarkLogicSinkConfig.java, src/main/java/com/marklogic/kafka/connect/sink/MarkLogicSinkTask.java, src/test/java/com/marklogic/kafka/connect/sink/AbstractIntegrationTest.java, src/test/java/com/marklogic/kafka/connect/sink/WriteTemporalDocumentTest.java, src/test/ml-config/databases/content-database.json, src/test/ml-config/databases/schemas-database.json, src/test/ml-config/temporal/axes/temporal-system-axis.json, src/test/ml-config/temporal/axes/temporal-valid-axis.json, src/test/ml-config/temporal/collections/kafka-temporal-collection.json
Resolves #50 . Also included an ml-gradle project for a test app, and now using marklogic-junit5 for integration tests that actually write data to ML.
=> Can now configure a temporal collection

README.md, config/marklogic-sink.properties, src/main/java/com/marklogic/kafka/connect/sink/BulkDataServicesSinkTask.java, src/main/java/com/marklogic/kafka/connect/sink/MarkLogicSinkConfig.java
Did some testing and made improvements to the docs, modified logging a bit, and added the properties to marklogic-sink.properties.
=> Tweaks to Bulk Data Services feature

gradle.properties, src/test/java/com/marklogic/kafka/connect/sink/AbstractIntegrationTest.java, src/test/ml-config/security/roles/minimal-user-role.json, src/test/ml-config/security/users/minimal-user.json
Resolves #75 . Realized in the process that we don't need to read the API declaration from the modules database, so going to submit a PR for that next.
=> Running tests as minimal user

src/main/java/com/marklogic/kafka/connect/source/MarkLogicSourceConfig.java, src/main/java/com/marklogic/kafka/connect/source/MarkLogicSourceConnector.java, src/main/java/com/marklogic/kafka/connect/source/RowBatcherSourceTask.java, src/test/java/com/marklogic/kafka/connect/sink/AbstractIntegrationSinkTest.java, src/test/java/com/marklogic/kafka/connect/sink/HandleInvalidSinkRecordTest.java, src/test/java/com/marklogic/kafka/connect/sink/HandleWriteFailureTest.java, src/test/java/com/marklogic/kafka/connect/sink/WriteFromKafkaTest.java, src/test/java/com/marklogic/kafka/connect/sink/WriteRecordWithKafkaMetadataTest.java, src/test/java/com/marklogic/kafka/connect/sink/WriteTemporalDocumentTest.java, src/test/java/com/marklogic/kafka/connect/sink/WriteViaBulkDataServicesTest.java, src/test/java/com/marklogic/kafka/connect/source/AbstractIntegrationSourceTest.java, src/test/java/com/marklogic/kafka/connect/source/MarkLogicSourceConnectorConfigBuilder.java, src/test/java/com/marklogic/kafka/connect/source/ReadRowsViaOpticDslKafkaTest.java
Initially, just create a barebones Source connector. Querying MarkLogic will come next.
=> DEVEXP-108: Read rows via Optic DSL statement.

CONTRIBUTING.md, src/test/java/com/marklogic/kafka/connect/source/ReadRowsViaOpticDslKafkaTest.java
Also added clarification about installing Gradle.
Also removed an unused import - I was trying to run the tests on Java 17, and it failed on the unused import which I guess doesn't exist in Java 17.
=> Added note to contributing about Java version

src/main/java/com/marklogic/kafka/connect/source/AbstractRowBatchBuilder.java, src/main/java/com/marklogic/kafka/connect/source/CsvRowBatcherBuilder.java, src/main/java/com/marklogic/kafka/connect/source/JsonRowBatcherBuilder.java, src/main/java/com/marklogic/kafka/connect/source/MarkLogicSourceConfig.java, src/main/java/com/marklogic/kafka/connect/source/RowBatcherBuilder.java, src/main/java/com/marklogic/kafka/connect/source/RowBatcherSourceTask.java, src/main/java/com/marklogic/kafka/connect/source/XmlRowBatcherBuilder.java, src/test/java/com/marklogic/kafka/connect/source/AbstractIntegrationSourceTest.java, src/test/java/com/marklogic/kafka/connect/source/ReadCsvRowsTest.java, src/test/java/com/marklogic/kafka/connect/source/ReadRowsViaOpticDslTest.java, src/test/java/com/marklogic/kafka/connect/source/ReadRowsViaOpticSerializedTest.java, src/test/java/com/marklogic/kafka/connect/source/ReadXmlRowsTest.java
I'm considering creating an interface for the different types.
The implementations would replace some code in newRowBatcher() and also the onSuccess events.
=> DEVEXP-112: Read rows as XML or CSV

src/main/java/com/marklogic/kafka/connect/source/ConstraintValueStore.java, src/main/java/com/marklogic/kafka/connect/source/DslQueryHandler.java, src/main/java/com/marklogic/kafka/connect/source/InMemoryConstraintValueStore.java, src/main/java/com/marklogic/kafka/connect/source/MarkLogicConstraintValueStore.java, src/main/java/com/marklogic/kafka/connect/source/MarkLogicSourceConfig.java, src/main/java/com/marklogic/kafka/connect/source/QueryHandler.java, src/main/java/com/marklogic/kafka/connect/source/RowBatcherSourceTask.java, src/main/java/com/marklogic/kafka/connect/source/SerializedQueryHandler.java, src/test/java/com/marklogic/kafka/connect/AbstractIntegrationTest.java, src/test/java/com/marklogic/kafka/connect/source/AbstractIntegrationSourceTest.java, src/test/java/com/marklogic/kafka/connect/source/DslConstraintInjectionPollTest.java, src/test/java/com/marklogic/kafka/connect/source/MarkLogicSourceConfigTest.java, src/test/java/com/marklogic/kafka/connect/source/ReadRowsViaOpticDslTest.java, src/test/java/com/marklogic/kafka/connect/source/SerializedConstraintInjectionPollTest.java, src/test/java/com/marklogic/kafka/connect/source/StoreConstraintValueInMarkLogicTest.java, src/test/resources/singleAuthorSingleCitation.xml
DEVEXP-131: Configure constraining column value storage in MarkLogic
=> DEVEXP-131: Configure constraining column value storage in MarkLogic

README.md
=> Added constraint column docs

src/main/java/com/marklogic/kafka/connect/source/DslQueryHandler.java, src/main/java/com/marklogic/kafka/connect/source/QueryHandler.java, src/main/java/com/marklogic/kafka/connect/source/RowManagerSourceTask.java, src/main/java/com/marklogic/kafka/connect/source/SerializedQueryHandler.java
=> DEVEXP-139: View query in logged error when poll fails

manifest.json
DEVEXP-161: Update connector manifest.json file
=> DEVEXP-161: Update connector manifest.json file

src/main/java/com/marklogic/kafka/connect/source/SerializedQueryHandler.java, src/test/java/com/marklogic/kafka/connect/source/SerializedConstraintInjectionTest.java
Intent is to reduce the number of areas where Jackson can throw an exception. There's now just one place - when the handler is created, the String query is converted into a JsonNode, and then everything after that deals with the JsonNode.
=> Using JsonNode in serialized handler

README.md, src/main/java/com/marklogic/kafka/connect/source/AbstractPlanInvoker.java, src/main/java/com/marklogic/kafka/connect/source/CsvPlanInvoker.java, src/main/java/com/marklogic/kafka/connect/source/JsonPlanInvoker.java, src/main/java/com/marklogic/kafka/connect/source/MarkLogicSourceConfig.java, src/main/java/com/marklogic/kafka/connect/source/XmlPlanInvoker.java, src/test/java/com/marklogic/kafka/connect/source/AbstractIntegrationSourceTest.java, src/test/java/com/marklogic/kafka/connect/source/DslConstraintInjectionPollTest.java, src/test/java/com/marklogic/kafka/connect/source/ReadCsvRowsTest.java, src/test/java/com/marklogic/kafka/connect/source/ReadRowsViaOpticDslTest.java, src/test/java/com/marklogic/kafka/connect/source/ReadXmlRowsTest.java, src/test/java/com/marklogic/kafka/connect/source/SerializedConstraintInjectionPollTest.java, src/test/java/com/marklogic/kafka/connect/source/StoreConstraintValueInMarkLogicTest.java
And there's a new option to include them if desired.
=> DEVEXP-182: Column types are now excluded by default

build.gradle
Avoids a vulnerability in Spring 5.3.18
=> Updating DHF dependency

src/main/java/com/marklogic/kafka/connect/DefaultDatabaseClientConfigBuilder.java, src/main/java/com/marklogic/kafka/connect/sink/WriteBatcherSinkTask.java, src/main/java/com/marklogic/kafka/connect/source/AbstractPlanInvoker.java, src/main/java/com/marklogic/kafka/connect/source/CsvPlanInvoker.java, src/main/java/com/marklogic/kafka/connect/source/DocumentWriteOperationBuilder.java, src/main/java/com/marklogic/kafka/connect/source/DslQueryHandler.java, src/main/java/com/marklogic/kafka/connect/source/JsonPlanInvoker.java, src/main/java/com/marklogic/kafka/connect/source/SerializedQueryHandler.java, src/main/java/com/marklogic/kafka/connect/source/XmlPlanInvoker.java
Most/all of these looked safe, but switching to StringUtils for consistency and to ensure that an empty string can't cause an issue.
=> More StringUtils sanity checking

src/main/java/com/marklogic/kafka/connect/sink/RunFlowWriteBatchListener.java, src/main/java/com/marklogic/kafka/connect/sink/WriteBatcherSinkTask.java
The 1.9.0 Wiki page has been updated to include a note about the DHF support.
=> Fixed two sonar code smells

LICENSE.txt, NOTICE.txt
Updated year from 2022 to 2023; ignore the whitespace changes.
=> Updated license/notice

CODEOWNERS, CONTRIBUTING.md
Added a CODEOWNERS file for fun too.
=> Updated Confluent Platform setup instructions

build.gradle, src/test/java/com/marklogic/kafka/connect/source/StoreConstraintValueInMarkLogicTest.java
Still need to update DH - that will be a later PR.
I'm going to move Confluent Platform to a Docker cluster first.
=> Updating all dependencies

build.gradle, docs/writing-data.md, src/main/java/com/marklogic/kafka/connect/sink/DefaultSinkRecordConverter.java, src/main/java/com/marklogic/kafka/connect/sink/MarkLogicSinkConfig.java, src/test/java/com/marklogic/kafka/connect/sink/ConvertSinkRecordTest.java
Does testing this way make sense?
=> Can now include Kafka headers in the document metadata

CONTRIBUTING.md, gradle.properties
Also added a little publishing information to the CONTRIBUTING file.
=> Update the new snapshot version

.copyrightconfig, .env, Jenkinsfile
Also updating the copyright check configuration.
=> MLE-24538 - Changing the MarkLogic 12 Docker image again.
