marklogic/kafka-marklogic-connector

AWS-CloudFormation/CloudFormation-QuickStart.md
AWS-CloudFormation/cloudFormationTemplates/justTheResources.json
AWS-CloudFormation/cloudFormationTemplates/readyToGo.json
gradle.properties

I updated AWS-CloudFormation/cloudFormationTemplates/* with newer AMI and added some steps to CloudFormation-QuickStart.md

update to CloudFormation templates and instructions

---

CONTRIBUTING.md
README.md
build.gradle
gradle.properties
src/test/resources/confluent/datagen-purchases-connector.json
src/test/resources/confluent/marklogic-purchases-connector.json

Before 1.7.0 is released, the CONTRIBUTING guide will be updated to capture how to develop and test with regular Kafka. And the README will be updated to focus on using a connector release in both Kafka and Confluent.

Added CONTRIBUTING guide with Confluent Platform instructions

---

AWS-CloudFormation/s3Resources/marklogic-sink.properties
CONTRIBUTING.md
README.md
build.gradle
config/marklogic-sink.properties
gradle.properties
src/main/java/com/marklogic/kafka/connect/DefaultDatabaseClientConfigBuilder.java
src/main/java/com/marklogic/kafka/connect/sink/MarkLogicSinkConfig.java
src/main/java/com/marklogic/kafka/connect/sink/MarkLogicSinkTask.java
src/test/java/com/marklogic/kafka/connect/BuildDatabaseClientConfigTest.java
src/test/resources/confluent/marklogic-purchases-connector.json

Resolves #57. 
- Updated docs for each config option so they're the same in all 3 places - README, marklogic-sink.properties, and MarkLogicSinkConfig
- Updated the CONTRIBUTING guide for testing with Apache Kafka
- Updated the README so it is focused on using the connectors as opposed to developing/testing them (more updates will happen to this before 1.7.0 is released)

Reworked docs for config options

---

README.md
config/marklogic-sink.properties
src/main/java/com/marklogic/kafka/connect/ConfigUtil.java
src/main/java/com/marklogic/kafka/connect/DefaultDatabaseClientConfigBuilder.java
src/main/java/com/marklogic/kafka/connect/sink/DefaultSinkRecordConverter.java
src/main/java/com/marklogic/kafka/connect/sink/MarkLogicSinkConfig.java
src/main/java/com/marklogic/kafka/connect/sink/MarkLogicSinkTask.java
src/main/java/com/marklogic/kafka/connect/sink/WriteFailureHandler.java
src/test/java/com/marklogic/kafka/connect/sink/AbstractIntegrationTest.java
src/test/java/com/marklogic/kafka/connect/sink/ConvertSinkRecordTest.java
src/test/java/com/marklogic/kafka/connect/sink/HandleWriteFailureTest.java
src/test/java/com/marklogic/kafka/connect/sink/WriteRecordWithKafkaMetadataTest.java

Resolves #31 . 
- Moved batch failure logging into a separate WriteFailureHandler class
- Added ConfigUtil.getBoolean to account for boolean options having null values, got rid of some boilerplate with this

Can now include Kafka metadata on doc and log it when a failure occurs

---

src/main/java/com/marklogic/kafka/connect/sink/BulkDataServicesSinkTask.java
src/main/java/com/marklogic/kafka/connect/sink/WriteBatcherSinkTask.java

These need to be public so that Kafka can instantiate them via reflection

Making task classes public again

---

README.md
config/marklogic-sink.properties
gradle.properties
src/main/java/com/marklogic/kafka/connect/sink/BulkDataServicesSinkTask.java
src/main/java/com/marklogic/kafka/connect/sink/MarkLogicSinkConfig.java
src/main/java/com/marklogic/kafka/connect/sink/MarkLogicSinkConnector.java
src/test/java/com/marklogic/kafka/connect/sink/WriteViaBulkDataServicesTest.java
src/test/ml-config/security/roles/minimal-user-role.json
src/test/ml-modules/root/example/bulk-endpoint.api

This avoids requiring the ML user to have an eval privilege. 
The connector user now just needs to configure the endpoint URI and an optional batch size. The Bulk DS endpoint must still have an API declaration in the modules database, as that's required by Bulk DS. But the connector now builds an API declaration in memory based on the user's inputs and the known set of params, thus avoiding having to read from the modules database.

Reworked Bulk DS approach to avoid reading from modules database

---

src/test/ml-config/security/roles/minimal-user-role.json

Still need the rest-extension-user role so that the test user can read the modules.

Fixing Bulk DS tests

---

build.gradle
src/test/java/com/marklogic/kafka/connect/sink/AbstractIntegrationTest.java
src/test/java/com/marklogic/kafka/connect/sink/ConvertSinkRecordTest.java
src/test/java/com/marklogic/kafka/connect/sink/MarkLogicSinkConnectorConfigBuilder.java
src/test/java/com/marklogic/kafka/connect/sink/WriteFromKafkaTest.java
src/test/resources/logback.xml

Integrate Kafka-Junit into the project by creating a simple test of the existing ML connector functionality

DEVEXP-102: Integrate Kafka-Junit into the project for testing

---

build.gradle
src/main/java/com/marklogic/kafka/connect/source/MarkLogicSourceConfig.java
src/test/java/com/marklogic/kafka/connect/AbstractIntegrationTest.java
src/test/java/com/marklogic/kafka/connect/source/AbstractIntegrationSourceTest.java
src/test/java/com/marklogic/kafka/connect/source/MarkLogicSourceConfigTest.java
src/test/java/com/marklogic/kafka/connect/source/ReadRowsViaOpticDslKafkaTest.java
src/test/java/com/marklogic/kafka/connect/source/ReadRowsViaOpticDslTest.java

Adjusted minimum wait time to be zero, and "read" tests now use that so they can run as fast as possible

Tests now run as a minimal user

---

CONTRIBUTING.md
README.md
build.gradle
src/main/java/com/marklogic/kafka/connect/sink/MarkLogicSinkConfig.java
src/main/java/com/marklogic/kafka/connect/source/MarkLogicSourceConfig.java
src/main/java/com/marklogic/kafka/connect/source/RowBatcherSourceTask.java
src/test/java/com/marklogic/kafka/connect/source/ReadRowsViaOpticDslTest.java
src/test/ml-schemas/tde/purchases.json
src/test/resources/confluent/datagen-purchases-source.json
src/test/resources/confluent/marklogic-purchases-sink.json
src/test/resources/confluent/marklogic-purchases-source.json

This isn't complete, but should be enough to help someone get started with QA and kicking the tires on the source connector.
Summary:
- Renamed the Confluent test files so they either end in "-sink" or "-source" to make them more self-documenting
- Added some TODO's to the README where we'll need to fill stuff in later
- Changed ordered in Config classes so that connection properties show up first
- Modified some of the source config props based on language I pulled from the RowBatcher javadoc
- Modified the SourceRecord so that the JSON is stringified; will figure out how to return a JsonNode later
- Added "purchases" TDE for the demo source connector to use
- Changed demo files to use "kafka-test-user"

DEVEXP-126: Initial readme/contributing for source connector

---

src/main/java/com/marklogic/kafka/connect/source/RowBatcherSourceTask.java
src/test/java/com/marklogic/kafka/connect/source/ReadRowsViaOpticDslTest.java

Changes:
- Moved the try/catch to `poll()` so that `null` can be returned for a known server bug
- Changed the test to not always load data so it's easier to test the condition where no data exists
- Added another assertion to the "does not start with fromView" test, as it looks like we get a reliable error message for that

Added fix for known server bug

---

src/main/java/com/marklogic/kafka/connect/MarkLogicConfig.java
src/main/java/com/marklogic/kafka/connect/sink/MarkLogicSinkConfig.java
src/test/java/com/marklogic/kafka/connect/BuildDatabaseClientConfigTest.java

For a property with recommenders and validators, when the ConfigDef.NO_DEFAULT_VALUE is used as the default value, the property is becoming a required property in the ConfigDef. So I used an empty string as the default value.

DEVEXP-95: View recommendations and validation errors for certain sink config properties

---

build.gradle
gradle.properties
src/main/java/com/marklogic/kafka/connect/source/MarkLogicSourceConfig.java
src/main/java/com/marklogic/kafka/connect/source/RowBatcherSourceTask.java
src/test/resources/confluent/datagen-purchases-source.json
src/test/resources/confluent/marklogic-purchases-source.json

Made a few changes to make manual testing easier for now - disabled the datagen/sink connectors until we want to test them again; added a second forest to the test app for more realistic performance testing; tweaked the source connector to make it easier to test. 
Some of the logging additions will likely be removed, just added them to again make manual testing in CP easier for now.

Added Recommended for output format, plus logging

---

src/main/java/com/marklogic/kafka/connect/source/XmlRowBatcherBuilder.java
src/test/resources/confluent/marklogic-purchases-source.json

Also changed default batch size in marklogic-purchases-source to match what's in MarkLogicSourceConfig

Making TransformerFactory thread-safe

---

src/main/java/com/marklogic/kafka/connect/source/MarkLogicSourceConfig.java
src/test/java/com/marklogic/kafka/connect/source/MarkLogicSourceConfigTest.java

This fixes a bug where the Validator was forcing a value for the DSL and Serialized plans.

DEVEXP-111: Read rows via Optic serialized plan

---

CONTRIBUTING.md
build.gradle
gradle.properties
src/main/java/com/marklogic/kafka/connect/source/RowBatcherSourceTask.java
src/main/java/com/marklogic/kafka/connect/source/SerializedQueryHandler.java
src/test/java/com/marklogic/kafka/connect/source/debug/InsertAuthors.java

Can use `./gradlew insertAuthors -PauthorIds=6,7,8` to quickly insert new authors with user-defined IDs.

Logging tweaks, plus new testing tool for inserting authors

---

Jenkinsfile
build.gradle
src/main/java/com/marklogic/kafka/connect/source/CsvPlanInvoker.java
src/main/java/com/marklogic/kafka/connect/source/DslQueryHandler.java
src/main/java/com/marklogic/kafka/connect/source/JsonPlanInvoker.java
src/main/java/com/marklogic/kafka/connect/source/PlanInvoker.java
src/main/java/com/marklogic/kafka/connect/source/QueryHandler.java
src/main/java/com/marklogic/kafka/connect/source/RowBatcherSourceTask.java
src/main/java/com/marklogic/kafka/connect/source/SerializedQueryHandler.java
src/main/java/com/marklogic/kafka/connect/source/XmlPlanInvoker.java
src/test/java/com/marklogic/kafka/connect/source/ReadCsvRowsTest.java
src/test/java/com/marklogic/kafka/connect/source/ReadRowsViaOpticDslTest.java
src/test/java/com/marklogic/kafka/connect/source/ReadXmlRowsTest.java
src/test/resources/confluent/marklogic-employees-source.json

Consensus was that the downsides of RowBatcher - can only use fromView; errors happening in the background; confusion over what "batchSize" refers to - were not worth the potential benefit in performance. That's because once RowBatcher is noticeably faster than RowManager, the user is likely pulling back enough rows to run out of memory / Java heap space due to a massive List. 
This leaves all the RowBatcher support in place for now. Main addition is a `PlanInvoker` that does what `RowBatcherBuilder` effectively did, which is to choose the correct handle, invoke a plan, and convert the results into source records. 
Once this is merged, I'll submit a PR to remove all the RB support and rename the task to RowManagerSourceTask. Having that all in one commit/PR will make it easy to pull from …

Switching from RowBatcher to RowManager

---

src/main/java/com/marklogic/kafka/connect/source/DslQueryHandler.java
src/main/java/com/marklogic/kafka/connect/source/RowManagerSourceTask.java
src/test/java/com/marklogic/kafka/connect/source/AbstractIntegrationSourceTest.java
src/test/java/com/marklogic/kafka/connect/source/DslConstraintInjectionPollTest.java
src/test/java/com/marklogic/kafka/connect/source/DslConstraintInjectionTest.java
src/test/java/com/marklogic/kafka/connect/source/ReadRowsViaOpticDslTest.java
src/test/java/com/marklogic/kafka/connect/source/SerializedConstraintInjectionPollTest.java
src/test/java/com/marklogic/kafka/connect/source/StoreConstraintValueInMarkLogicTest.java
src/test/ml-config/databases/content-database.json
src/test/ml-schemas/tde/authors-TDE.tdej

New tests to start covering all the Optic data access functions.
Take particular notice of "pullDataUsingFromLexicons". This one doesn't just verify the injection, but also uses the injection to retrieve limited data.
Also take notice of BALANCED_PARENS_REGEX_PATTERN and it's use in DslQueryHandler.injectConstraintIntoQuery. I believe it gives me the first op function (no matter what it contains).

Accessor tests

---

manifest.json

Changed description to address sink/source; removed version requirements from it since it's in the "requirements" section.
Changed "Kafka MarkLogic to "MarkLogic Kafka" as that's the term used in the README.

DEVEXP-161 Slight tweak to manifest file

---

README.md
src/main/java/com/marklogic/kafka/connect/source/DslQueryHandler.java
src/main/java/com/marklogic/kafka/connect/source/MarkLogicSourceConfig.java

I renamed "row.limit" to "rowLimit" as I think the latter is consistent with the existing "outputFormat" option. Also collapsed the `appendLimitToQuery` method as it was only used in one place (I think this was formerly used by a test, but no longer is).

Added docs for rowLimit

---

README.md
src/main/java/com/marklogic/kafka/connect/sink/AbstractSinkTask.java
src/main/java/com/marklogic/kafka/connect/sink/BulkDataServicesSinkTask.java
src/main/java/com/marklogic/kafka/connect/sink/RunFlowWriteBatchListener.java
src/main/java/com/marklogic/kafka/connect/sink/WriteBatcherSinkTask.java
src/main/java/com/marklogic/kafka/connect/source/DslQueryHandler.java
src/main/java/com/marklogic/kafka/connect/source/MarkLogicConstraintValueStore.java
src/main/java/com/marklogic/kafka/connect/source/RowManagerSourceTask.java
src/main/java/com/marklogic/kafka/connect/source/SerializedQueryHandler.java
src/test/resources/logback.xml

Added README section on source connector logging.
Moved DLQ section in README to the bottom so that it's within the sink connector section and not in a section specific to DMSDK or Bulk Data Services.

Adjusted most source logging to be at DEBUG level

---

src/main/java/com/marklogic/kafka/connect/source/DslQueryHandler.java
src/main/java/com/marklogic/kafka/connect/source/MarkLogicConstraintValueStore.java
src/main/java/com/marklogic/kafka/connect/source/QueryHandlerUtil.java
src/main/java/com/marklogic/kafka/connect/source/SerializedQueryHandler.java

Both the DSL and serialized handlers do the same thing now. Tried a base class for providing the common behavior, but that felt a little over-engineered, so resurrected QueryHandlerUtil and added a static convenience method there instead. 
Also modified the catch block in MarkLogicConstraintValueStore to catch any exception and throw the same error. 
For testing, I had to manually force an error in order to get executeMaxValuePlan to fail - verified that the error message is correctly constructed.

Throwing error when max value query fails

---

README.md
src/main/java/com/marklogic/kafka/connect/source/CsvPlanInvoker.java
src/main/java/com/marklogic/kafka/connect/source/JsonPlanInvoker.java
src/main/java/com/marklogic/kafka/connect/source/KeyGenerator.java
src/main/java/com/marklogic/kafka/connect/source/NullKeyGenerator.java
src/main/java/com/marklogic/kafka/connect/source/TimestampKeyGenerator.java
src/main/java/com/marklogic/kafka/connect/source/UuidKeyGenerator.java
src/main/java/com/marklogic/kafka/connect/source/XmlPlanInvoker.java
src/test/java/com/marklogic/kafka/connect/source/AbstractIntegrationSourceTest.java

Also adjusted the `KeyGenerator` interface to not require a row number so that the plan invokers don't have to manage that; the timestamp generator can easily manage that itself. In addition, a new generator is constructed each time one or more rows are returned. 
Added a README section for key strategy as well.

DEVEXP-127: Using ML server timestamp for key strategy

---

src/main/java/com/marklogic/kafka/connect/source/ConstraintValueStore.java

Reported by sonar, as SimpleDateFormat is not thread-safe

Making date format a local variable

---

src/main/java/com/marklogic/kafka/connect/source/DslQueryHandler.java
src/test/java/com/marklogic/kafka/connect/source/DslConstraintInjectionPollTest.java
src/test/java/com/marklogic/kafka/connect/source/DslConstraintInjectionTest.java
src/test/java/com/marklogic/kafka/connect/source/StoreConstraintValueInMarkLogicTest.java
src/test/resources/confluent/marklogic-employees-source.json

This is primarily paranoia based on a fear of something not working if a query uses op.col in some cases but not in all cases.

Using op.col consistently

---

src/main/java/com/marklogic/kafka/connect/sink/DefaultSinkRecordConverter.java
src/main/java/com/marklogic/kafka/connect/sink/idstrategy/DefaultStrategy.java
src/main/java/com/marklogic/kafka/connect/sink/idstrategy/HashedJSONPathsStrategy.java
src/main/java/com/marklogic/kafka/connect/sink/idstrategy/HashedKafkaMetaStrategy.java
src/main/java/com/marklogic/kafka/connect/sink/idstrategy/IdStrategy.java
src/main/java/com/marklogic/kafka/connect/sink/idstrategy/IdStrategyFactory.java
src/main/java/com/marklogic/kafka/connect/sink/idstrategy/JSONPathStrategy.java
src/main/java/com/marklogic/kafka/connect/sink/idstrategy/KafkaMetaStrategy.java
src/main/java/com/marklogic/kafka/connect/source/DocumentWriteOperationBuilder.java
src/main/java/com/marklogic/kafka/connect/source/RecordContent.java

The IdStrategy is Kakfa-specific, and DocumentWriteOperationBuilder can be used for inspiration for something reusable in the Java Client.

Moved Kafka-specific classes out of client.ext package

---

src/main/java/com/marklogic/kafka/connect/sink/AbstractSinkTask.java

"debug" is helpful on the source side for seeing some info on each poll call. But the "Processing record" message in the sink connector shows up for every single sink record; that can quickly become overwhelming. So shifted that to "trace".

Using trace for some verbose sink logging

---

README.md
build.gradle
src/main/java/com/marklogic/kafka/connect/DefaultDatabaseClientConfigBuilder.java
src/main/java/com/marklogic/kafka/connect/MarkLogicConfig.java
src/test/java/com/marklogic/kafka/connect/BuildDatabaseClientConfigTest.java

Fairly simple matter of just adding two config options and passing them along to the existing class that collects inputs for constructing a client.

Added support for MarkLogic Cloud auth

---

README.md
build.gradle
src/main/java/com/marklogic/kafka/connect/source/MarkLogicSourceConnector.java
src/test/java/com/marklogic/kafka/connect/source/CreateTasksTest.java

Summary:
1. Bumped to ml-javaclient/app-deployer 4.5.0, which uses Java Client 6.1.0
2. Clarified why a user may have a serialized plan in the README (I really think the Java Client is the main use case here; if a user is using qconsole, wouldn't they just use a DSL?).
3. Modified the source connector to ignore a task count greater than 1.

Little bits of beta feedback

---

CONTRIBUTING.md
README.md
build.gradle
config/marklogic-sink.properties
config/marklogic-source.properties

See the comment in build.gradle about excluding Jackson dependencies from the connector archive. 
Bumped up a couple test dependencies while I was at it.

DHF integration in sink connector now works with Confluent

---

Jenkinsfile
src/main/java/com/marklogic/kafka/connect/source/QueryHandlerUtil.java
src/test/java/com/marklogic/kafka/connect/source/AbstractIntegrationSourceTest.java
src/test/java/com/marklogic/kafka/connect/source/QueryHandlerUtilTest.java

We were catching the error when the query succeeds but brings back an unexpected result. We now catch the error when the query fails. This is in response to the `pullDataUsingFromSearchDocs` test failing due to a change in the server where the "select" call fails when used with "fromSearchDocs".

Improving error message for when max value query fails

---

build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties

Addresses the vulnerability in okio, which is fixed in Java Client 6.3.0. 
Had to bump Gradle to 8 to allow for uber jar to be built, now that Jackson 2.15 is used by the Java Client (we did the same thing for our Spark connector). 
Everything in the CONTRIB ran fine, no issues encountered.

DEVEXP-652 Bumped to Java Client 6.3.0 to address vulnerability

---

CONTRIBUTING.md
build.gradle
docker-compose.yml
src/test/confluent-platform-example/docker-compose.yml
src/test/resources/confluent/marklogic-authors-source.json
src/test/resources/confluent/marklogic-employees-source.json
src/test/resources/confluent/marklogic-purchases-sink.json
src/test/resources/confluent/marklogic-purchases-source.json

Removed Confluent Platform install and command-line stuff from the CONTRIBUTING file.
The command-line version is still in the user guide. Do we want to change that, or add the Docker version as an alternative?

Switch to Confluent Platform via Docker

---

build.gradle

org.eclipse.jetty:jetty-http:12.1.1
io.netty:netty-all:4.2.6.Final

MLE-24529 - Force newer jetty and netty libraries to avoid CVEs
